import { Photo, SearchResponse } from "@/utils/interfaces";

export const PhotoItem: Photo = {
  id: 1,
  width: 100,
  height: 80,
  url: 'string',
  photographer: 'string',
  photographer_url: 'string',
  photographer_id: 111,
  avg_color: 'string',
  src: {
    original: 'string',
    large2x: 'string',
    large:  'string',
    medium:  'string',
    small: 'string',
    portrait: 'string',
    landscape: 'string',
    tiny: 'string',
  },
  alt: 'string',
}
export const PhotoData = [
  {
    id: 1,
    width: 100,
    height: 80,
    url: 'string',
    photographer: 'string',
    photographer_url: 'string',
    photographer_id: 111,
    avg_color: 'string',
    src: {
      original: 'string',
      large2x: 'string',
      large:  'string',
      medium:  'string',
      small: 'string',
      portrait: 'string',
      landscape: 'string',
      tiny: 'string',
    },
    alt: 'string',
  },
  {
    id: 2,
    width: 100,
    height: 80,
    url: 'string',
    photographer: 'string',
    photographer_url: 'string',
    photographer_id: 111,
    avg_color: 'string',
    src: {
      original: 'string',
      large2x: 'string',
      large:  'string',
      medium:  'string',
      small: 'string',
      portrait: 'string',
      landscape: 'string',
      tiny: 'string',
    },
    alt: 'string',
  },
  {
    id: 3,
    width: 100,
    height: 80,
    url: 'string',
    photographer: 'string',
    photographer_url: 'string',
    photographer_id: 111,
    avg_color: 'string',
    src: {
      original: 'string',
      large2x: 'string',
      large:  'string',
      medium:  'string',
      small: 'string',
      portrait: 'string',
      landscape: 'string',
      tiny: 'string',
    },
    alt: 'string',
  },
]

export const ResponseData: SearchResponse = {
  page: 1,
  per_page: 10,
  photos: PhotoData,
  total_results: 124,
  prev_page: '',
  next_page: ''
}
